[package]
name = "ic_rusqlite_bench_backend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
candid = "0.8"
ic-cdk = "0.8.1"
hex = "0.4.3"
serde = "1.0.163"
serde_json = "1.0"
ic-cdk-timers = "0.2" # Feel free to remove this dependency if you don't need timers
ic-wasi-polyfill = { git = "https://github.com/wasm-forge/ic-wasi-polyfill", rev = "d2faf36155c454d7c87272d953c1c2dc0b6bc1b6" }
rusqlite = { git = "https://github.com/rusqlite/rusqlite", version = "0.29.0", features = ["bundled", "wasm32-wasi-vfs"] }
